<?php
  // Get some configuration constants and functions
  require("../admin/inc/config.inc");
  require("../admin/inc/classes.inc");
  require("../admin/inc/functions.inc");

  $sock = db_connect();

  // Set to 0 before registering the session so that anyone sneaky
  // enough to pass the "advertiser_id" as a URL parameter will have it
  // overridden.  It can only be written properly by the login page.
  $advertiser_id = 0;
  session_register("advertiser_id");

  $advertiser = new Advertiser (0, $advertiser_id, $sock);

  if (!$advertiser->id) {
    echo "Invalid advertiser ID.";
    exit();
  }
?>

<html>

<head>
<title><?php echo OWNER_NAME ?> AdServ Client Ad List</title>
</head>

<body bgcolor="#ffffff">
<blockquote>
<font face="Arial, MS Sans Serif, Helvetica" size=2>

  <table border=0 cellpadding=0 cellspacing=0 width=90%>
  <tr>
  <td>
  <font face="Arial, MS Sans Serif, Helvetica" size=2>
  <font color=green size=+2><b><?php echo OWNER_NAME ?> AdServ Client Ad List</b></font><br>
  <hr noshade size=2>
  </td>
  </tr>
  </table>


  <table border=0 cellpadding=0 cellspacing=0 width=90%>
  <tr>
  <td><a href="logout.phtml"><img border=0 src="img/button-logout.gif" alt="Logout"></a></td>
  <td align=right>
  <font face="Arial, MS Sans Serif, Helvetica" size=2>
  <b>Advertiser:</b> <?php echo $advertiser->fullname ?> <i>(<?php echo $advertiser->username ?>)</i>
  </font>
  </td>
  </tr>
  </table>

<p>


<h3>Active Ad List</h3>

Click the ad ID for detailed information.<p>

<form action="nothing" method="post">

<table border=1 width=90% cellspacing=0 cellpadding=4>
<tr bgcolor=#000000>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
ID
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Location
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Alt Text
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Freq.
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Imp. Prchsd.
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Imp. Used
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Clicks
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Click %
</font></th>
</tr>

<?php
  // Display all active ads for the current advertiser
  $query = "SELECT * FROM ads
            WHERE advertiser_id = " . $advertiser->id . " AND active = 1
            ORDER BY id";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    exit();
  }

  $num_rows = mysql_num_rows($sql_result);

  if ($num_rows > 0) {
    for ($a = 0; $a < $num_rows; $a++) {
      if ($a % 2) {
        $fc = "#000000";
        $bc = "#e0f0e0";
      }
      else {
        $fc = "#000000";
        $bc = "#d9d9d9";
      }

      $ad = new Ad(mysql_fetch_row($sql_result));
      $location = new Location(0, $ad->location_id, $sock);
      $percentage = ($ad->clickthroughs / $ad->imp_used) * 100;
      printf("
<tr bgcolor=\"%s\">
<td align=center>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=2 color=\"%s\">
<b><a href=\"viewad.phtml?id=%d\">%d</a></b>
</font>
</td>
<td>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
<input type=text size=14 value=\"%s\">
</font>
</td>
<td align=center>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%d
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%.2f
</font>
</td>
</tr>\n",
        $bc, 
        $fc, $ad->id, $ad->id, 
        $fc, $location->title, 
        $fc, $ad->alttext,
        $fc, $ad->frequency,
        $fc, format_numbers($ad->imp_purchased),
        $fc, format_numbers($ad->imp_used),
        $fc, format_numbers($ad->clickthroughs),
        $fc, $percentage);
        //date("d M Y H:i:s", $location->opened));
    }
  }
?>

</table>

<p>

<h3>Inactive Ad List</h3>

<table border=1 width=90% cellspacing=0 cellpadding=4>
<tr bgcolor=#000000>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
ID
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Location
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Alt Text
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Freq.
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Imp. Prchsd.
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Imp. Used
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Clicks
</font></th>
<th><font face="Arial, MS Sans Serif, Helvetica" size=2 color=#d9d9d9>
Click %
</font></th>
</tr>

<?php
  // Display all active ads for the current advertiser
  $query = "SELECT * FROM ads
            WHERE advertiser_id = " . $advertiser->id . " AND active = 0
            ORDER BY id";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    exit();
  }

  $num_rows = mysql_num_rows($sql_result);

  if ($num_rows > 0) {
    for ($a = 0; $a < $num_rows; $a++) {
      if ($a % 2) {
        $fc = "#000000";
        $bc = "#e0f0e0";
      }
      else {
        $fc = "#000000";
        $bc = "#d9d9d9";
      }

      $ad = new Ad(mysql_fetch_row($sql_result));
      $location = new Location(0, $ad->location_id, $sock);
      $percentage = ($ad->clickthroughs / $ad->imp_used) * 100;
      printf("
<tr bgcolor=\"%s\">
<td align=center>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=2 color=\"%s\">
<b><a href=\"viewad.phtml?id=%d\">%d</a></b>
</font>
</td>
<td>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
<input type=text size=14 value=\"%s\">
</font>
</td>
<td align=center>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%d
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%s
</font>
</td>
<td align=right>
<font face=\"Arial, MS Sans Serif, Helvetica\" size=1 color=\"%s\">
%.2f
</font>
</td>
</tr>\n",
        $bc, 
        $fc, $ad->id, $ad->id, 
        $fc, $location->title, 
        $fc, $ad->alttext,
        $fc, $ad->frequency,
        $fc, format_numbers($ad->imp_purchased),
        $fc, format_numbers($ad->imp_used),
        $fc, format_numbers($ad->clickthroughs),
        $fc, $percentage);
        //date("d M Y H:i:s", $location->opened));
    }
  }
?>

</table>

<p>

</form>

  <table border=0 cellpadding=0 cellspacing=0 width=90%>
  <tr><td colspan=2><hr noshade size=2></td></tr>
  <tr>
  <td>
  <font face="Arial, MS Sans Serif, Helvetica" size=2>
  <i>AdServ version <?php echo ADSERV_VERSION ?>
  </font>
  </td>
  <td align=right>
  <font face="Arial, MS Sans Serif, Helvetica" size=2>
  <i><b><a href="mailto:<?php echo EMAIL_SENDER_ADDRESS ?>"><font color=green><?php echo EMAIL_SENDER_ADDRESS ?></font></a></b></i>
  </font>
  </td>
  </tr>
  </table>

</body>
</html>

