<?php
  // Define some global config paramaters
  define("ADSERV_VERSION", "1.2");
  define("OWNER_NAME", "Some Store");
  define("OWNER_ADDRESS", "Some Store
123 Oak St
Springfield, ON  N9X 1X1

Tel: (519) 555-4444
Fax: (519) 555-1234
Email: contact@example.com");

  define("EMAIL_SENDER_NAME", "Some Store AdServer");
  define("EMAIL_SENDER_ADDRESS", "contact@example.com");

  // Define some connection parameters
  define("DATABASE_HOST", "localhost");
  define("DATABASE_USER", "username");
  define("DATABASE_PASSWD", "password");
  define("DATABASE_NAME", "AdServ");

  define("ADMIN_USERNAME", "admin");
  define("ADMIN_PASSWORD", "password");
  define("REDIR_SCRIPT", "http://www.example.com/AdServ/click.phtml");
?>
